### ISSUE TITLE
non-ASCII characters in README breaking setup.py (py3.5, Win10)

### ISSUE THREAD

**Issue by joefutrelle** [pyoceans/pocean-core#19]
Under Anaconda / Python 3.5 in Win10, running `setup.py` fails because of the non-ASCII icons (e.g., the ocean wave) in the README file. Removing those fixes the problem. However, the icons are nice, so I'm hoping there's a workaround.

**Comment by kwilcox** [comment]
Should be able to encode as ascii pretty easily after loading the README file in setup.py. I'll take a stab

**Comment by kwilcox** [comment]
@joefutrelle can you try with the latest `master`?

**Comment by joefutrelle** [comment]
Tried it, got the same error :(

```
$ python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    long_description    = readme(),
  File "setup.py", line 13, in readme
    return f.read().encode('ascii', errors='ignore').decode()
  File "C:\Users\joefutrelle\Anaconda2\envs\deleteme2\lib\encodings\cp1252.py",
line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 5: charac
ter maps to <undefined>
```

**Comment by kwilcox** [comment]
Tough for me to test without a Windows computer! Can you try this:

```python
import string
...

def readme():
    with open('README.md') as f:
        return "".join([x for x in f.read() if x in string.printable ]
```

**Comment by joefutrelle** [comment]
Tried that, got the same error.

**Comment by joefutrelle** [comment]
It's f.read() that's raising the error

**Comment by kwilcox** [comment]
ah ha! try this:

```
def readme():
    with open('README.md', 'rb') as f:
        return f.read().decode('ascii', errors='ignore')
```

**Comment by joefutrelle** [comment]
That works.

**Comment by kwilcox** [comment]
OK great. Can you try:

```
def readme():
    with open('README.md', 'rb') as f:
        return f.read().decode('utf-8', errors='ignore')
```

**Comment by joefutrelle** [comment]
That works too.

**Comment by kwilcox** [comment]
OK should be all set: https://github.com/pyoceans/pocean-core/commit/f9ee920b402356555de1198bceb2b26b321c5cbf
